import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import Layout from '@/components/Layout';
import { useI18n } from '@/i18n';
import { navApi, navigationRequest, json, type BuildingGraph } from '@/lib/navigationApi';
import type { Building, Floor, Place } from '@shared/navigation';

type Organization={id:string;name:string;type:string;verification_status:string;member_role?:string};
type Preview={valid:boolean;errors:string[];warnings:string[];summary:{buildings:number;floors:number;places:number;nodes:number;edges:number;transitions:number}};
type ImportRow={id:string;status:string;preview:Preview|string;created_at:string};
type AuditRow={id:string;action:string;entity_type:string;created_at:string};
type VersionRow={version:number;source_type:string;changes:number;created_at:string};
const input='min-h-12 w-full rounded-xl border border-amber-200/40 bg-stone-950 px-3 py-2 text-white';
const button='min-h-12 rounded-xl bg-amber-300 px-5 py-2 font-bold text-stone-950 disabled:opacity-50';
const panel='rounded-2xl border border-amber-200/25 bg-stone-900 p-5';
const copy={
  ar:{title:'مدير خرائط بصيرة الداخلية',org:'المؤسسة',building:'المبنى',createOrg:'إنشاء مؤسسة (المشرف العام)',createBuilding:'إضافة مبنى للمؤسسة',members:'إدارة العضوية',floors:'الطوابق',places:'الأماكن',nodes:'العقد',edges:'الحواف',community:'مساهمات المجتمع للمراجعة',versions:'إصدارات الخريطة',audit:'سجل التعديلات',import:'استيراد خريطة رسمية',preview:'تحقق ومعاينة',approve:'اعتماد صريح',errors:'أخطاء',warnings:'تنبيهات',pending:'مسودة بانتظار الاعتماد',ready:'تم الحفظ',failed:'تعذر إكمال الطلب أو لا تملك الصلاحية.',reference:'يدعم الاستيراد المنظم Basira JSON v1 فقط. ملفات IMDF وGeoJSON وSVG وPDF وCAD وBIM تحتاج مراجعة أو أداة تحويل معتمدة؛ لا تُحوَّل تلقائيًا إلى مسار رسمي.'},
  en:{title:'Basira Indoor Manager',org:'Organization',building:'Building',createOrg:'Create organization (global admin)',createBuilding:'Add organization building',members:'Manage membership',floors:'Floors',places:'Places',nodes:'Nodes',edges:'Edges',community:'Community contributions for review',versions:'Map versions',audit:'Change log',import:'Official map import',preview:'Validate and preview',approve:'Explicit approval',errors:'Errors',warnings:'Warnings',pending:'Draft awaiting approval',ready:'Saved',failed:'Request failed or permission denied.',reference:'Only structured Basira JSON v1 import is supported. IMDF, GeoJSON, SVG, PDF, CAD, and BIM need human review or a verified converter; they are not automatically promoted to an official route.'},
  'zh-CN':{title:'Basira 室内地图管理',org:'机构',building:'建筑',createOrg:'创建机构（全局管理员）',createBuilding:'添加建筑',members:'成员管理',floors:'楼层',places:'地点',nodes:'节点',edges:'边',community:'待审核社区贡献',versions:'地图版本',audit:'更改记录',import:'正式地图导入',preview:'验证与预览',approve:'明确批准',errors:'错误',warnings:'提示',pending:'待批准草稿',ready:'已保存',failed:'请求失败或无权限。',reference:'仅支持结构化 Basira JSON v1。IMDF、GeoJSON、SVG、PDF、CAD 和 BIM 需要人工审核或可靠转换器，不能自动成为正式路线。'},
};

export default function IndoorManager(){
  const {lang}=useI18n(),t=copy[lang]??copy.ar;
  const [organizations,setOrganizations]=useState<Organization[]>([]),[globalAdmin,setGlobalAdmin]=useState(false),[orgId,setOrgId]=useState(''),[buildingId,setBuildingId]=useState('');
  const [buildings,setBuildings]=useState<Building[]>([]),[floors,setFloors]=useState<Floor[]>([]),[places,setPlaces]=useState<Place[]>([]),[graph,setGraph]=useState<BuildingGraph|null>(null);
  const [imports,setImports]=useState<ImportRow[]>([]),[preview,setPreview]=useState<Preview|null>(null),[versions,setVersions]=useState<VersionRow[]>([]),[events,setEvents]=useState<AuditRow[]>([]),[contributions,setContributions]=useState<{id:string;type:string;status:string}[]>([]);
  const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[orgType,setOrgType]=useState('UNIVERSITY'),[buildingName,setBuildingName]=useState(''),[buildingType,setBuildingType]=useState('University'),[floorName,setFloorName]=useState(''),[floorNumber,setFloorNumber]=useState('0'),[memberId,setMemberId]=useState(''),[memberRole,setMemberRole]=useState('viewer'),[importText,setImportText]=useState('');
  const current=organizations.find(item=>item.id===orgId),canManage=globalAdmin||current?.member_role==='organization_admin',canMap=canManage||current?.member_role==='mapper',canReview=canManage||current?.member_role==='reviewer';
  const refreshOrgs=async()=>{const data=await navigationRequest<{organizations:Organization[];globalAdmin:boolean}>('/organizations');setOrganizations(data.organizations);setGlobalAdmin(data.globalAdmin);};
  const refreshOrg=async(id:string)=>{if(!id){setBuildings([]);return;}const [b,a]=await Promise.all([navigationRequest<{buildings:Building[]}>(`/organizations/${id}/buildings`),navigationRequest<{events:AuditRow[]}>(`/organizations/${id}/audit`)]);setBuildings(b.buildings);setEvents(a.events);};
  const refreshBuilding=async(id:string)=>{if(!id||!orgId){setGraph(null);setFloors([]);setPlaces([]);return;}const base=`/organizations/${orgId}/buildings/${id}`;
    const [f,p,g,i,v,c]=await Promise.all([navApi.floors(id),navApi.places(id),navApi.graph(id),navigationRequest<{imports:ImportRow[]}>(`${base}/imports`),navigationRequest<{versions:VersionRow[]}>(`${base}/versions`),navigationRequest<{contributions:{id:string;type:string;status:string}[]}>(`/shared-map/buildings/${id}/contributions`).catch(()=>({contributions:[]}))]);
    setFloors(f.floors);setPlaces(p.places);setGraph(g);setImports(i.imports);setVersions(v.versions);setContributions(c.contributions);
  };
  useEffect(()=>{void refreshOrgs().catch(()=>setNotice(t.failed));},[]);
  useEffect(()=>{setBuildingId('');void refreshOrg(orgId).catch(()=>setNotice(t.failed));},[orgId]);
  useEffect(()=>{void refreshBuilding(buildingId).catch(()=>setNotice(t.failed));},[orgId,buildingId]);
  const run=async(task:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await task();setNotice(t.ready);}catch{setNotice(t.failed);}finally{setBusy(false);}};
  const createOrganization=(event:FormEvent)=>{event.preventDefault();void run(async()=>{await navigationRequest('/organizations',json('POST',{name,type:orgType}));setName('');await refreshOrgs();});};
  const createBuilding=(event:FormEvent)=>{event.preventDefault();void run(async()=>{const result=await navigationRequest<{building:Building}>(`/organizations/${orgId}/buildings`,json('POST',{name:buildingName,buildingType}));setBuildingName('');await refreshOrg(orgId);setBuildingId(result.building.id);});};
  const createFloor=(event:FormEvent)=>{event.preventDefault();void run(async()=>{await navigationRequest(`/buildings/${buildingId}/floors`,json('POST',{name:floorName,floorNumber:Number(floorNumber)}));setFloorName('');await refreshBuilding(buildingId);});};
  const grantMember=(event:FormEvent)=>{event.preventDefault();void run(async()=>{await navigationRequest(`/organizations/${orgId}/members`,json('POST',{userId:memberId,role:memberRole}));setMemberId('');await refreshOrg(orgId);});};
  const createPreview=(event:FormEvent)=>{event.preventDefault();void run(async()=>{const document=JSON.parse(importText) as unknown;const response=await fetch(`/api/navigation/organizations/${orgId}/buildings/${buildingId}/imports`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(document)});const result=await response.json() as {report?:Preview};if(result.report)setPreview(result.report);if(!response.ok)throw new Error('invalid_import');await refreshBuilding(buildingId);});};
  const approve=(id:string)=>void run(async()=>{await navigationRequest(`/organizations/${orgId}/buildings/${buildingId}/imports/${id}/approve`,json('POST',{}));await refreshBuilding(buildingId);await refreshOrg(orgId);});
  const reject=(id:string)=>void run(async()=>{await navigationRequest(`/organizations/${orgId}/buildings/${buildingId}/imports/${id}/reject`,json('POST',{}));await refreshBuilding(buildingId);await refreshOrg(orgId);});
  const counts=preview?.summary;
  return <Layout><div className="container space-y-6 py-10 text-stone-100"><Link href="/navigation" className="text-amber-200 underline">Navigation</Link><h1 className="text-3xl font-bold">{t.title}</h1><p role="status" aria-live="polite" className="min-h-7 text-amber-200">{notice}</p>
    {globalAdmin&&<form className={panel+' grid gap-3 sm:grid-cols-3'} onSubmit={createOrganization}><h2 className="sm:col-span-3 text-xl font-bold">{t.createOrg}</h2><label>{t.org}<input className={input} required maxLength={255} value={name} onChange={event=>setName(event.target.value)}/></label><label>Type<select className={input} value={orgType} onChange={event=>setOrgType(event.target.value)}>{['UNIVERSITY','SCHOOL','HOSPITAL','AIRPORT','MALL','GOVERNMENT','COMPANY','DISABILITY_CENTER','OTHER'].map(type=><option key={type}>{type}</option>)}</select></label><button className={button} disabled={busy}>Create</button></form>}
    <label className="block">{t.org}<select className={input} value={orgId} onChange={event=>setOrgId(event.target.value)}><option value="">—</option>{organizations.map(org=><option key={org.id} value={org.id}>{org.name} · {org.type}</option>)}</select></label>
    {orgId&&<><p>{current?.verification_status} · {current?.member_role??(globalAdmin?'global admin':'viewer')}</p>{canManage&&<div className="grid gap-4 md:grid-cols-2"><form className={panel+' space-y-3'} onSubmit={createBuilding}><h2 className="text-xl font-bold">{t.createBuilding}</h2><label>{t.building}<input className={input} required value={buildingName} onChange={event=>setBuildingName(event.target.value)}/></label><label>Type<select className={input} value={buildingType} onChange={event=>setBuildingType(event.target.value)}>{['University','School','Hospital','Airport','Mall','Government','Office','PublicBuilding','Other'].map(type=><option key={type}>{type}</option>)}</select></label><button className={button} disabled={busy}>Create</button></form><form className={panel+' space-y-3'} onSubmit={grantMember}><h2 className="text-xl font-bold">{t.members}</h2><label>User ID<input className={input} required value={memberId} onChange={event=>setMemberId(event.target.value)}/></label><label>Role<select className={input} value={memberRole} onChange={event=>setMemberRole(event.target.value)}>{['viewer','mapper','reviewer',...(globalAdmin?['organization_admin']:[])].map(role=><option key={role}>{role}</option>)}</select></label><button className={button} disabled={busy}>Save</button></form></div>}
      <label className="block">{t.building}<select className={input} value={buildingId} onChange={event=>setBuildingId(event.target.value)}><option value="">—</option>{buildings.map(item=><option key={item.id} value={item.id}>{item.name} · {item.verificationStatus}</option>)}</select></label>
      {buildingId&&<><div className="grid gap-4 md:grid-cols-2"><section className={panel}><h2 className="text-xl font-bold">{t.floors} · {floors.length}</h2><ul className="mt-3 space-y-1">{floors.map(item=><li key={item.id}>{item.floorNumber}: {item.name}</li>)}</ul>{canMap&&graph?.building.verificationStatus!=='OFFICIAL'&&<form className="mt-4 grid gap-3" onSubmit={createFloor}><label>Floor number<input className={input} type="number" min={-20} max={300} required value={floorNumber} onChange={event=>setFloorNumber(event.target.value)}/></label><label>Floor name<input className={input} required maxLength={255} value={floorName} onChange={event=>setFloorName(event.target.value)}/></label><button className={button} disabled={busy}>Add floor</button></form>}</section><section className={panel}><h2 className="text-xl font-bold">{t.places} · {places.length}</h2><ul className="mt-3 space-y-1">{places.slice(0,30).map(item=><li key={item.id}>{item.name} {item.roomNumber} · {floors.find(f=>f.id===item.floorId)?.name}</li>)}</ul></section><section className={panel}><h2 className="text-xl font-bold">{t.nodes} · {graph?.nodes.length??0}</h2><ul className="mt-3 space-y-1">{graph?.nodes.slice(0,30).map(item=><li key={item.id}>{item.nodeType} ({item.x}, {item.y})</li>)}</ul></section><section className={panel}><h2 className="text-xl font-bold">{t.edges} · {graph?.edges.length??0}</h2><ul className="mt-3 space-y-1">{graph?.edges.slice(0,30).map(item=><li key={item.id}>{item.pathType} · {item.distanceMeters} m</li>)}</ul></section></div>
        <section className={panel}><h2 className="text-xl font-bold">{t.versions}</h2><ul className="mt-3 space-y-1">{versions.map(item=><li key={item.version}>v{item.version} · {item.source_type} · {item.changes} changes</li>)}</ul></section>
        {canReview&&<section className={panel}><h2 className="text-xl font-bold">{t.community}</h2><ul className="mt-3 space-y-1">{contributions.map(item=><li key={item.id}>{item.type} · {item.status} · <Link href="/navigation/shared-map" className="text-amber-200 underline">Review</Link></li>)}</ul></section>}
        <section className={panel}><h2 className="text-xl font-bold">{t.import}</h2><p className="mt-2 text-stone-300">{t.reference}</p>{canMap&&<form className="mt-4 space-y-3" onSubmit={createPreview}><label className="block">Basira JSON v1<textarea className={input+' min-h-48 font-mono text-sm'} required value={importText} onChange={event=>setImportText(event.target.value)}/></label><button className={button} disabled={busy}>{t.preview}</button></form>}
          {preview&&<div className="mt-4" role="status" aria-live="polite"><p>{counts?.buildings} buildings · {counts?.floors} floors · {counts?.places} places · {counts?.nodes} nodes · {counts?.edges} edges · {counts?.transitions} transitions</p><h3 className="mt-3 font-bold">{t.errors} ({preview.errors.length})</h3><ul>{preview.errors.map((error,index)=><li key={index}>{error}</li>)}</ul><h3 className="mt-3 font-bold">{t.warnings} ({preview.warnings.length})</h3><ul>{preview.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></div>}
          <ul className="mt-4 space-y-3">{imports.map(item=><li key={item.id} className="rounded border border-amber-200/25 p-3">{item.status} · {item.created_at} · {t.pending}{item.status==='PENDING'&&canReview&&<><button className={button+' ms-3'} disabled={busy} onClick={()=>approve(item.id)}>{t.approve}</button><button className="ms-3 min-h-12 rounded-xl border border-amber-200/40 px-5" disabled={busy} onClick={()=>reject(item.id)}>Reject</button></>}</li>)}</ul>
        </section></>}
      <section className={panel}><h2 className="text-xl font-bold">{t.audit}</h2><ul className="mt-3 space-y-1">{events.slice(0,40).map(item=><li key={item.id}>{item.action} · {item.entity_type} · {item.created_at}</li>)}</ul></section></>}
  </div></Layout>;
}
