import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import Layout from '@/components/Layout';
import { useMessages } from '@/i18n';
import { navigationMessages } from '@/i18n/locales/navigation';
import { navApi, navigationRequest, json, type BuildingGraph } from '@/lib/navigationApi';
import { permissionService } from '@/lib/permissionService';
import { buildingTypes, placeTypes, nodeTypes, type Building, type Floor, type Place } from '@shared/navigation';

const input='min-h-12 w-full rounded-xl border border-amber-200/35 bg-stone-950 px-3 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber-300';
const button='min-h-12 rounded-xl bg-amber-300 px-5 py-2 font-bold text-stone-950 hover:bg-amber-200';
const panel='rounded-2xl border border-amber-200/20 bg-stone-900/80 p-5';
const field=(label:string, value:string, set:(value:string)=>void, required=false, type='text')=><label className="block">{label}{required?' *':''}<input className={input} type={type} step={type==='number'?'any':undefined} required={required} value={value} onChange={e=>set(e.target.value)}/></label>;

export default function NavigationAdmin() {
  const t=useMessages(navigationMessages);
  const [role,setRole]=useState<string|null>(null); const [loaded,setLoaded]=useState(false);
  const [buildings,setBuildings]=useState<Building[]>([]); const [buildingId,setBuildingId]=useState('');
  const [floors,setFloors]=useState<Floor[]>([]); const [places,setPlaces]=useState<Place[]>([]); const [graph,setGraph]=useState<BuildingGraph|null>(null);
  const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const [buildingName,setBuildingName]=useState(''),[organization,setOrganization]=useState(''),[buildingType,setBuildingType]=useState<typeof buildingTypes[number]>('University'),[address,setAddress]=useState(''),[description,setDescription]=useState(''),[latitude,setLatitude]=useState(''),[longitude,setLongitude]=useState(''),[floorCount,setFloorCount]=useState('');
  const [floorNumber,setFloorNumber]=useState('0'),[floorName,setFloorName]=useState(''),[floorDescription,setFloorDescription]=useState(''),[plan,setPlan]=useState('');
  const [placeName,setPlaceName]=useState(''),[room,setRoom]=useState(''),[placeType,setPlaceType]=useState<typeof placeTypes[number]>('CLASSROOM'),[floorId,setFloorId]=useState(''),[placeDescription,setPlaceDescription]=useState(''),[aliases,setAliases]=useState(''),[department,setDepartment]=useState(''),[localX,setLocalX]=useState(''),[localY,setLocalY]=useState(''),[doorDirection,setDoorDirection]=useState(''),[accessibility,setAccessibility]=useState('');
  const [nodeFloor,setNodeFloor]=useState(''),[nodePlace,setNodePlace]=useState(''),[nodeType,setNodeType]=useState<typeof nodeTypes[number]>('POINT'),[nodeX,setNodeX]=useState(''),[nodeY,setNodeY]=useState('');
  const [fromNode,setFromNode]=useState(''),[toNode,setToNode]=useState(''),[distance,setDistance]=useState(''),[pathType,setPathType]=useState<'CORRIDOR'|'DOOR'|'STAIRS'|'RAMP'|'ELEVATOR'|'OTHER'>('CORRIDOR');
  const reloadBuildings=()=>navApi.buildings().then(data=>setBuildings(data.buildings));
  const reloadBuilding=async(id:string)=>{if(!id){setFloors([]);setPlaces([]);setGraph(null);return;}const [f,p,g]=await Promise.all([navApi.floors(id),navApi.places(id),navApi.graph(id)]);setFloors(f.floors);setPlaces(p.places);setGraph(g);};
  useEffect(()=>{navApi.access().then(data=>{setRole(data.role);setLoaded(true);if(data.role)reloadBuildings().catch(()=>setNotice(t.failed));}).catch(()=>{setLoaded(true);setNotice(t.failed);});},[]);
  useEffect(()=>{reloadBuilding(buildingId).catch(()=>setNotice(t.failed));},[buildingId]);
  const run=async(task:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await task();setNotice(t.savedSuccess);}catch{setNotice(t.failed);}finally{setBusy(false);}};
  const createBuilding=(event:FormEvent)=>{event.preventDefault();run(async()=>{const response=await navigationRequest<{building:Building}>('/buildings',json('POST',{name:buildingName,organizationName:organization||null,buildingType,address:address||null,description:description||null,latitude:latitude?Number(latitude):null,longitude:longitude?Number(longitude):null,numberOfFloors:floorCount?Number(floorCount):null}));await reloadBuildings();setBuildingId(response.building.id);setBuildingName('');});};
  const useLocation=async()=>{try{const p=await permissionService.currentLocation();setLatitude(String(p.latitude));setLongitude(String(p.longitude));}catch{setNotice(t.noLocation);}};
  const createFloor=(event:FormEvent)=>{event.preventDefault();run(async()=>{await navigationRequest(`/buildings/${buildingId}/floors`,json('POST',{floorNumber:Number(floorNumber),name:floorName,description:floorDescription||null,floorPlanReference:plan||null}));await reloadBuilding(buildingId);setFloorName('');setFloorNumber(String(Number(floorNumber)+1));});};
  const createPlace=(event:FormEvent,again=false)=>{event.preventDefault();run(async()=>{await navigationRequest(`/buildings/${buildingId}/places`,json('POST',{name:placeName,roomNumber:room||null,placeType,floorId,description:placeDescription||null,aliases:aliases.split(/[,،]/).map(s=>s.trim()).filter(Boolean),departmentName:department||null,localX:localX?Number(localX):null,localY:localY?Number(localY):null,entranceDirection:doorDirection||null,accessibilityInformation:accessibility||null}));await reloadBuilding(buildingId);setPlaceName('');setRoom('');setAliases('');if(!again){setFloorId('');setPlaceDescription('');setDepartment('');setLocalX('');setLocalY('');setDoorDirection('');setAccessibility('');}});};
  const createNode=(event:FormEvent)=>{event.preventDefault();run(async()=>{await navigationRequest(`/buildings/${buildingId}/nodes`,json('POST',{floorId:nodeFloor,placeId:nodePlace||null,x:Number(nodeX),y:Number(nodeY),nodeType,accessibilityLevel:'UNKNOWN'}));await reloadBuilding(buildingId);setNodeX('');setNodeY('');});};
  const createEdge=(event:FormEvent)=>{event.preventDefault();run(async()=>{await navigationRequest(`/buildings/${buildingId}/edges`,json('POST',{fromNodeId:fromNode,toNodeId:toNode,distanceMeters:Number(distance),pathType,accessibilityLevel:'UNKNOWN'}));await reloadBuilding(buildingId);setFromNode('');setToNode('');setDistance('');});};
  if(!loaded)return <Layout><div className="container py-10">{t.loading}</div></Layout>;
  if(!role)return <Layout><div className="container space-y-4 py-10 text-stone-100"><h1 className="text-3xl font-black">{t.buildMap}</h1><p role="alert">{t.adminOnly}</p><Link href="/navigation" className="text-amber-300 underline">{t.title}</Link></div></Layout>;
  return <Layout><div className="container space-y-7 py-10 text-stone-100"><Link href="/navigation" className="text-amber-300 underline">{t.title}</Link><h1 className="text-3xl font-black">{t.buildMap}</h1><p role="status" aria-live="polite" className="min-h-6 text-amber-200">{notice}</p>
    <section className={panel}><h2 className="mb-4 text-xl font-bold">{t.addBuilding}</h2><form onSubmit={createBuilding} className="grid gap-4 sm:grid-cols-2">{field(t.buildingName,buildingName,setBuildingName,true)}{field(t.organization,organization,setOrganization)}<label>{t.buildingType} *<select className={input} value={buildingType} onChange={e=>setBuildingType(e.target.value as typeof buildingType)}>{buildingTypes.map(key=><option key={key} value={key}>{t.buildingTypes[key]}</option>)}</select></label>{field(t.address,address,setAddress)}{field(t.floorsCount,floorCount,setFloorCount,false,'number')}{field(t.description,description,setDescription)}{field(t.latitude,latitude,setLatitude,false,'number')}{field(t.longitude,longitude,setLongitude,false,'number')}<button type="button" className={button} onClick={useLocation}>{t.useCurrent}</button><button className={button} disabled={busy}>{t.save}</button></form></section>
    <label className="block">{t.building}<select className={input} value={buildingId} onChange={e=>setBuildingId(e.target.value)}><option value="">{t.chooseBuilding}</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
    {buildingId&&<>
      <section className={panel}><h2 className="mb-4 text-xl font-bold">{t.addFloors}</h2><form onSubmit={createFloor} className="grid gap-4 sm:grid-cols-2">{field(t.floorNumber,floorNumber,setFloorNumber,true,'number')}{field(t.floorName,floorName,setFloorName,true)}{field(t.description,floorDescription,setFloorDescription)}{field(t.floorPlan,plan,setPlan)}<button className={button} disabled={busy}>{t.save}</button></form><ul className="mt-4">{floors.map(f=><li key={f.id}>{f.name} ({f.floorNumber})</li>)}</ul></section>
      <section className={panel}><h2 className="mb-4 text-xl font-bold">{t.addPlaces}</h2><form id="place-form" onSubmit={createPlace} className="grid gap-4 sm:grid-cols-2">{field(t.placeName,placeName,setPlaceName,true)}{field(t.roomNumber,room,setRoom)}<label>{t.placeType} *<select className={input} value={placeType} onChange={e=>setPlaceType(e.target.value as typeof placeType)}>{placeTypes.map(key=><option key={key} value={key}>{t.placeTypes[key]}</option>)}</select></label><label>{t.floor} *<select className={input} required value={floorId} onChange={e=>setFloorId(e.target.value)}><option value="">{t.chooseFloor}</option>{floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{field(t.description,placeDescription,setPlaceDescription)}{field(t.aliases,aliases,setAliases)}{field(t.department,department,setDepartment)}{field(t.localX,localX,setLocalX,false,'number')}{field(t.localY,localY,setLocalY,false,'number')}{field(t.entranceDirection,doorDirection,setDoorDirection)}{field(t.accessibility,accessibility,setAccessibility)}<div className="flex flex-wrap gap-2 sm:col-span-2"><button className={button} disabled={busy}>{t.save}</button><button type="button" className={button} disabled={busy} onClick={()=>{const form=document.getElementById('place-form') as HTMLFormElement;if(form?.reportValidity())createPlace({preventDefault:()=>{}} as FormEvent,true);}}>{t.saveAndAdd}</button></div></form><p className="mt-4">{t.addPlaces}: {places.length}</p></section>
      <section className={panel}><h2 className="mb-4 text-xl font-bold">{t.buildMap}</h2><div className="grid gap-6 lg:grid-cols-2"><form onSubmit={createNode} className="grid gap-3"><h3 className="font-bold">{t.addNode}</h3><label>{t.floor} *<select className={input} required value={nodeFloor} onChange={e=>{setNodeFloor(e.target.value);setNodePlace('');}}><option value="">{t.chooseFloor}</option>{floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>{t.choosePlace}<select className={input} value={nodePlace} onChange={e=>setNodePlace(e.target.value)}><option value="">{t.choosePlace}</option>{places.filter(p=>p.floorId===nodeFloor).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t.nodeType}<select className={input} value={nodeType} onChange={e=>setNodeType(e.target.value as typeof nodeType)}>{nodeTypes.map(key=><option key={key} value={key}>{t.nodeTypes[key]}</option>)}</select></label>{field(t.localX,nodeX,setNodeX,true,'number')}{field(t.localY,nodeY,setNodeY,true,'number')}<button className={button} disabled={busy}>{t.addNode}</button></form>
        <form onSubmit={createEdge} className="grid gap-3"><h3 className="font-bold">{t.addEdge}</h3><label>{t.fromNode} *<select className={input} required value={fromNode} onChange={e=>setFromNode(e.target.value)}><option value="">{t.fromNode}</option>{graph?.nodes.map(n=><option key={n.id} value={n.id}>{t.nodeTypes[n.nodeType]} ({n.x}, {n.y}) · {floors.find(f=>f.id===n.floorId)?.name}</option>)}</select></label><label>{t.toNode} *<select className={input} required value={toNode} onChange={e=>setToNode(e.target.value)}><option value="">{t.toNode}</option>{graph?.nodes.map(n=><option key={n.id} value={n.id}>{t.nodeTypes[n.nodeType]} ({n.x}, {n.y}) · {floors.find(f=>f.id===n.floorId)?.name}</option>)}</select></label><label>{t.pathType}<select className={input} value={pathType} onChange={e=>setPathType(e.target.value as typeof pathType)}>{Object.entries(t.pathTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{field(t.distance,distance,setDistance,true,'number')}<button className={button} disabled={busy}>{t.addEdge}</button></form></div><p className="mt-4">{t.graphNodes}: {graph?.nodes.length??0} · {t.graphEdges}: {graph?.edges.length??0}</p></section>
    </>}
  </div></Layout>;
}
