import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import Layout from '@/components/Layout';
import { navApi, navigationRequest } from '@/lib/navigationApi';
import { emptyProposal, flushSharedMapQueue, observedEvidence, sharedMapApi, type IssueSubmission, type Submission } from '@/lib/sharedMap';
import type { Building, Floor, Place } from '@shared/navigation';
import type { ContributionType, IssueDuration, IssueType, MapDecision, SharedMapContribution } from '@shared/sharedMap';

const panel='rounded-2xl border border-amber-200/25 bg-stone-900 p-5';
const input='min-h-12 w-full rounded-xl border border-amber-200/40 bg-stone-950 px-3 py-2 text-white';
const button='min-h-12 rounded-xl bg-amber-300 px-5 py-2 font-bold text-stone-950 disabled:opacity-50';
const secondary='min-h-12 rounded-xl border border-amber-300/60 px-4 py-2 font-bold text-amber-100 disabled:opacity-50';
const statusLabel:Record<string,string>={PENDING:'مكتشف، بانتظار الأدلة',CORROBORATING:'قيد التأكيد المستقل',COMMUNITY_VERIFIED:'أكدته مساهمات مستقلة، بانتظار المراجعة',OFFICIAL:'رسمي بعد مراجعة المسؤول',REJECTED:'مرفوض',CONFLICTED:'توجد معلومات متعارضة',STALE:'دليل قديم'};
type Candidate={id:string;type:ContributionType;status:string;proposal:{name:string|null;roomNumber:string|null;floorId:string;x:number|null;y:number|null};independentConfirmations:number;confidence:number};
type Issue={id:string;type:IssueType;duration:IssueDuration;description:string;status:string};

export default function SharedMap(){
  const [buildings,setBuildings]=useState<Building[]>([]),[buildingId,setBuildingId]=useState(()=>sessionStorage.getItem('basira-current-building')??'');
  const [floors,setFloors]=useState<Floor[]>([]),[places,setPlaces]=useState<Place[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[contributions,setContributions]=useState<SharedMapContribution[]>([]),[issues,setIssues]=useState<Issue[]>([]);
  const [role,setRole]=useState<string|null>(null),[version,setVersion]=useState(1),[history,setHistory]=useState<{version:number;action:string;entity_type:string;entity_id:string}[]>([]);
  const [floorId,setFloorId]=useState(''),[name,setName]=useState(''),[room,setRoom]=useState(''),[x,setX]=useState(''),[y,setY]=useState(''),[placeType,setPlaceType]=useState<Place['placeType']>('ROOM'),[type,setType]=useState<ContributionType>('PLACE'),[targetPlaceId,setTargetPlaceId]=useState('');
  const [issueType,setIssueType]=useState<IssueType>('PLACE_MISSING'),[issueDuration,setIssueDuration]=useState<IssueDuration>('UNKNOWN'),[issueDescription,setIssueDescription]=useState('');
  const [consent,setConsent]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [reviewActions,setReviewActions]=useState<Record<string,MapDecision>>({}),[resolveConflicts,setResolveConflicts]=useState<Record<string,boolean>>({});
  const [details,setDetails]=useState<Record<string,{current:Record<string,unknown>|null;conflicts:{id:string;kind:string;status:string}[]}>>({});
  const [detailId,setDetailId]=useState('');
  useEffect(()=>{navApi.buildings().then(result=>setBuildings(result.buildings)).catch(()=>setNotice('تعذر تحميل المباني.'));navApi.access().then(result=>setRole(result.role)).catch(()=>setRole(null));},[]);
  const load=async(id:string)=>{
    if(!id)return;
    const [f,p,v,c]=await Promise.all([navApi.floors(id),navApi.places(id),sharedMapApi.version(id),navigationRequest<{candidates:Candidate[]}>(`/shared-map/buildings/${id}/candidates`)]);
    setFloors(f.floors);setPlaces(p.places);setVersion(v.version);setCandidates(c.candidates);setFloorId(previous=>f.floors.some(floor=>floor.id===previous)?previous:f.floors[0]?.id??'');
    if(role){const [contributionResult,issueResult]=await Promise.all([sharedMapApi.contributions(id),sharedMapApi.issues(id)]);setContributions(contributionResult.contributions);setIssues(issueResult.issues);if(role==='admin')setHistory((await sharedMapApi.history(id)).history);}
  };
  useEffect(()=>{void load(buildingId).catch(()=>setNotice('تعذر تحميل بيانات الخريطة المشتركة.'));},[buildingId,role]);
  useEffect(()=>{const flush=()=>{void flushSharedMapQueue().then(result=>{if(result.sent)setNotice(`أُرسلت ${result.sent} مساهمة محفوظة بعد عودة الاتصال.`);});};window.addEventListener('online',flush);flush();return()=>window.removeEventListener('online',flush);},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!consent||!buildingId||!floorId||!Number.isFinite(Number(x))||!Number.isFinite(Number(y))||!x.trim()||!y.trim()){setNotice('حدد المبنى والطابق والإحداثيات ووافق على مشاركة بيانات المكان العامة فقط.');return;}
    const proposal=emptyProposal(floorId);proposal.name=name.trim();proposal.roomNumber=room.trim()||null;proposal.placeType=placeType;proposal.x=Number(x);proposal.y=Number(y);proposal.targetPlaceId=targetPlaceId||null;
    const body:Submission={buildingId,type,source:'USER_MANUAL',proposal,evidence:observedEvidence(floorId,proposal.x,proposal.y,.6),idempotencyKey:crypto.randomUUID(),consent:true};
    setBusy(true);try{const result=await sharedMapApi.submit(body);setNotice('queued'in result?'حُفظ الطلب لهذه الجلسة وسيُرسل عند عودة الاتصال.':'أُرسلت المساهمة للمراجعة. ليست جزءًا من المسار الرسمي الآن.');setName('');setRoom('');setConsent(false);await load(buildingId);}catch{setNotice('تعذر إرسال المساهمة. تحقق من تسجيل الدخول وصحة الموقع.');}finally{setBusy(false);}
  };
  const report=async(event:FormEvent)=>{event.preventDefault();if(!consent||!buildingId||issueDescription.trim().length<8){setNotice('اكتب وصفًا كافيًا ووافق على إرسال التقرير.');return;}
    const body:IssueSubmission={buildingId,floorId:floorId||null,type:issueType,duration:issueDuration,description:issueDescription.trim(),targetPlaceId:targetPlaceId||null,targetEdgeId:null,idempotencyKey:crypto.randomUUID(),consent:true};
    setBusy(true);try{const result=await sharedMapApi.report(body);setNotice('queued'in result?'حُفظ التقرير لهذه الجلسة وسيُرسل عند عودة الاتصال.':'وصل التقرير إلى المراجعة؛ لا يغيّر الطريق تلقائيًا.');setIssueDescription('');setConsent(false);await load(buildingId);}catch{setNotice('تعذر إرسال التقرير.');}finally{setBusy(false);}
  };
  const confirm=async(candidate:Candidate)=>{if(!consent){setNotice('وافق على مشاركة ملاحظة مستقلة قبل التأكيد.');return;}setBusy(true);try{await sharedMapApi.confirm(candidate.id,observedEvidence(candidate.proposal.floorId,candidate.proposal.x,candidate.proposal.y,.6));setNotice('سُجل تأكيدك مرة واحدة؛ لا يصبح المكان رسميًا دون مراجعة.');await load(buildingId);}catch{setNotice('تعذر التأكيد أو سبق تسجيل مساهمتك.');}finally{setBusy(false);}};
  const review=async(item:SharedMapContribution,decision:'APPROVE'|'REJECT'|'MORE_EVIDENCE',action:MapDecision|null)=>{setBusy(true);try{await sharedMapApi.review(item.id,decision,action,Boolean(resolveConflicts[item.id]));setNotice('حُفظ قرار المراجعة.');await load(buildingId);}catch{setNotice('لم تُطبق المراجعة. تحقق من التعارضات وحقول المكان ونوع الإجراء.');}finally{setBusy(false);}};
  const rollback=async(version:number)=>{setBusy(true);try{await sharedMapApi.rollback(buildingId,version);setNotice('أُنشئ إصدار جديد يعكس التغييرات السابقة.');await load(buildingId);}catch{setNotice('تعذر التراجع؛ ربما تغيّر الكيان منذ ذلك الإصدار.');}finally{setBusy(false);}};
  return <Layout><main className="container space-y-6 py-10 text-stone-100"><Link href="/navigation" className="text-amber-200 underline">العودة إلى التنقل</Link><h1 className="text-3xl font-black">خريطة بصيرة المشتركة</h1>
    <p>ساهم بالمعلومات العامة عن الأماكن. الأسماء المحفوظة في «أماكني» تبقى خاصة ولا تُرسل تلقائيًا. لا ترسل صورة أو سجل حركة أو عنوان منزل. المساهمة المكتشفة لا تُستخدم كمسار رسمي قبل مراجعتها.</p>
    <label className="block max-w-xl">المبنى<select className={input} value={buildingId} onChange={e=>{setBuildingId(e.target.value);sessionStorage.setItem('basira-current-building',e.target.value);}}><option value="">اختر مبنى</option>{buildings.map(building=><option key={building.id} value={building.id}>{building.name}</option>)}</select></label>
    {buildingId&&<p className={panel}>إصدار الخريطة المعتمد: {version} · حالة خريطة المبنى: {buildings.find(item=>item.id===buildingId)?.mapStatus??'غير معروف'}. خذ حذرك عند نقص الخريطة أو تعارض المساهمات.</p>}
    <p role="status" aria-live="polite" className="text-amber-200">{notice}</p>
    {buildingId&&<><label className="block max-w-xl">الطابق<select className={input} value={floorId} onChange={e=>setFloorId(e.target.value)}>{floors.map(floor=><option key={floor.id} value={floor.id}>{floor.name}</option>)}</select></label>
      <label className="flex items-start gap-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-5 w-5"/>أوافق صراحة على إرسال معلومات هذا المكان العامة للمراجعة. لا تُرسل صورة الكاميرا أو سجلات الحركة أو هوية ظاهرة للآخرين.</label>
      <section className={panel}><h2 className="mb-3 text-xl font-bold">اقترح مكانًا أو تصحيحًا</h2><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">
        <label>نوع المساهمة<select className={input} value={type} onChange={e=>setType(e.target.value as ContributionType)}><option value="PLACE">مكان جديد</option><option value="PLACE_NAME_CHANGE">تغيير اسم</option><option value="PLACE_MOVED">مكان انتقل</option></select></label>
        <label>المكان الموجود إن كان تصحيحًا<select className={input} value={targetPlaceId} onChange={e=>setTargetPlaceId(e.target.value)}><option value="">مكان جديد</option>{places.map(place=><option key={place.id} value={place.id}>{place.name}</option>)}</select></label>
        <label>الاسم العام<input className={input} required value={name} onChange={e=>setName(e.target.value)} maxLength={255}/></label><label>رقم الغرفة<input className={input} value={room} onChange={e=>setRoom(e.target.value)} maxLength={80}/></label>
        <label>نوع المكان<select className={input} value={placeType} onChange={e=>setPlaceType(e.target.value as Place['placeType'])}>{['ROOM','CLASSROOM','OFFICE','LAB','RECEPTION','ELEVATOR','STAIRS','RESTROOM','ENTRANCE','EXIT','PHARMACY','CLINIC','OTHER'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label>X<input className={input} type="number" step="any" required value={x} onChange={e=>setX(e.target.value)}/></label><label>Y<input className={input} type="number" step="any" required value={y} onChange={e=>setY(e.target.value)}/></label></div>
        <p className="sm:col-span-2 text-sm text-stone-300">أدخل إحداثيات الخريطة الداخلية بعد تأكيد موقعك. لا تدّعِ دقة لا تملكها؛ يتطلب الاعتماد أدلة مستقلة ومراجعة مختص.</p><button className={button} disabled={busy||!consent}>إرسال للمراجعة</button>
      </form></section>
      <section className={panel}><h2 className="mb-3 text-xl font-bold">أبلغ عن مشكلة في الخريطة</h2><form onSubmit={report} className="grid gap-3 sm:grid-cols-2"><label>نوع المشكلة<select className={input} value={issueType} onChange={e=>setIssueType(e.target.value as IssueType)}>{['PLACE_MISSING','WRONG_NAME','PLACE_MOVED','ROAD_CLOSED','ELEVATOR_MISSING','WRONG_FLOOR','WRONG_ACCESSIBILITY','UNMARKED_STAIRS','BLIND_UNFRIENDLY','OTHER'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>المدة<select className={input} value={issueDuration} onChange={e=>setIssueDuration(e.target.value as IssueDuration)}><option value="UNKNOWN">غير معروف</option><option value="TEMPORARY">مؤقت</option><option value="PERSISTENT">مستمر</option></select></label><label className="sm:col-span-2">الوصف<textarea className={input} required minLength={8} maxLength={500} value={issueDescription} onChange={e=>setIssueDescription(e.target.value)}/></label><button className={button} disabled={busy||!consent}>إرسال التقرير</button></form><p className="mt-2 text-sm text-stone-300">العائق العابر مثل كرسي في الممر يُراجع كبلاغ مؤقت ولا يتحول إلى جدار دائم.</p></section>
      <section className={panel}><h2 className="mb-3 text-xl font-bold">أماكن قيد التحقق</h2>{candidates.length?<ul className="space-y-3">{candidates.map(candidate=><li key={candidate.id} className="rounded-xl border border-amber-200/30 p-3"><strong>{candidate.proposal.name??candidate.type}</strong> · {statusLabel[candidate.status]??candidate.status}<p className="text-sm text-stone-300">تأكيدات مستقلة: {candidate.independentConfirmations} · ثقة تقديرية: {candidate.confidence>=.75?'مرتفعة':candidate.confidence>=.5?'متوسطة':'منخفضة'}. هذه ليست دقة موقع أو تصريحًا بمسار آمن.</p><button className={secondary} disabled={busy||!consent} onClick={()=>confirm(candidate)}>أكد بعد ملاحظتي المستقلة</button></li>)}</ul>:<p>لا توجد مساهمات عامة معروضة.</p>}</section>
      {role&&<section className={panel}><h2 className="mb-3 text-xl font-bold">طابور المراجع</h2><p className="mb-3 text-sm">المراجعة الرسمية مسؤولة عن التغيير في خريطة B1. افحص التعارضات والموقع قبل الاعتماد.</p><ul className="space-y-4">{contributions.filter(item=>!['OFFICIAL','REJECTED'].includes(item.status)).map(item=><li key={item.id} className="rounded-xl border border-amber-200/30 p-3"><strong>{item.proposal.name??item.type}</strong> · {statusLabel[item.status]??item.status} · تعارضات {item.conflictCount}<p>المصدر: {item.source} · نوع: {item.type} · تأكيدات: {item.independentConfirmations} · ثقة: {item.confidence.toFixed(2)}</p><p>المقترح: الطابق {floors.find(floor=>floor.id===item.proposal.floorId)?.name??item.proposal.floorId} · ({item.proposal.x??'؟'}, {item.proposal.y??'؟'}) · {item.proposal.roomNumber??''}</p>{item.proposal.targetPlaceId&&<p>الحالي: {places.find(place=>place.id===item.proposal.targetPlaceId)?.name??'مكان موجود'} · {places.find(place=>place.id===item.proposal.targetPlaceId)?.roomNumber??''}</p>}<label className="mt-2 block">إجراء الاعتماد<select className={input} value={reviewActions[item.id]??(item.proposal.targetEdgeId?'CLOSE_EDGE':item.proposal.targetPlaceId?'UPDATE':'CREATE')} onChange={e=>setReviewActions(previous=>({...previous,[item.id]:e.target.value as MapDecision}))}>{['CREATE','UPDATE','MERGE','ALIAS','CLOSE_EDGE','REOPEN_EDGE'].map(action=><option key={action} value={action}>{action}</option>)}</select></label>{item.conflictCount>0&&<label className="mt-2 flex gap-2"><input type="checkbox" checked={Boolean(resolveConflicts[item.id])} onChange={e=>setResolveConflicts(previous=>({...previous,[item.id]:e.target.checked}))}/>راجعت التعارضات وأجيز حلها بهذا القرار</label>}<div className="mt-2 flex flex-wrap gap-2"><button className={button} disabled={busy||item.conflictCount>0&&!resolveConflicts[item.id]} onClick={()=>review(item,'APPROVE',reviewActions[item.id]??(item.proposal.targetEdgeId?'CLOSE_EDGE':item.proposal.targetPlaceId?'UPDATE':'CREATE'))}>اعتماد التغيير</button><button className={secondary} disabled={busy} onClick={()=>review(item,'MORE_EVIDENCE',null)}>اطلب أدلة</button><button className={secondary} disabled={busy} onClick={()=>review(item,'REJECT',null)}>ارفض</button></div></li>)}</ul>
        <div className="mt-5"><label>تفاصيل المساهمة والتعارضات<select className={input} value={detailId} onChange={e=>setDetailId(e.target.value)}><option value="">اختر مساهمة</option>{contributions.map(item=><option key={item.id} value={item.id}>{item.proposal.name??item.type} · {item.id.slice(0,8)}</option>)}</select></label><button className={secondary} disabled={!detailId} onClick={()=>void sharedMapApi.contribution(detailId).then(result=>setDetails(previous=>({...previous,[detailId]:result}))).catch(()=>setNotice('تعذر عرض تفاصيل المساهمة.'))}>عرض المعلومات الحالية والتعارضات</button>{detailId&&details[detailId]&&<div className="mt-3 rounded-xl border border-amber-200/25 p-3"><p>المعلومة الحالية في B1: {details[detailId].current?`${String(details[detailId].current?.name??'عنصر خريطة')} · ${String(details[detailId].current?.room_number??'')} · الطابق ${String(details[detailId].current?.floor_id??'')}`:'لا يوجد كيان مطابق'}</p><p>التعارضات: {details[detailId].conflicts.length?details[detailId].conflicts.map(conflict=>`${conflict.kind} (${conflict.status})`).join('، '):'لا توجد'}</p></div>}</div>
        <h3 className="mt-6 font-bold">بلاغات الخريطة</h3><ul className="space-y-2">{issues.filter(issue=>issue.status==='PENDING').map(issue=><li key={issue.id} className="rounded-xl border border-amber-200/25 p-3">{issue.type} · {issue.duration} · {issue.description}<div className="mt-2 flex gap-2"><button className={secondary} onClick={()=>sharedMapApi.reviewIssue(issue.id,'REVIEWED').then(()=>load(buildingId))}>تمت المراجعة</button><button className={secondary} onClick={()=>sharedMapApi.reviewIssue(issue.id,'DISMISSED').then(()=>load(buildingId))}>استبعاد</button></div></li>)}</ul>
      </section>}
      {role==='admin'&&<section className={panel}><h2 className="mb-3 text-xl font-bold">إصدارات الخريطة والتراجع</h2><ul className="space-y-2">{history.map((entry,index)=><li key={`${entry.version}-${index}`}>الإصدار {entry.version}: {entry.action} · {entry.entity_type} <button className={secondary} disabled={busy} onClick={()=>rollback(entry.version)}>تراجع إلى ما قبل هذا التغيير</button></li>)}</ul></section>}
    </>}
  </main></Layout>;
}
