import { toExamLanguage, type ExamLanguage } from "../shared/ocr";

export { toExamLanguage };
export type { ExamLanguage };

export const aiFallback: Record<ExamLanguage, string> = {
  ar: "عذراً، لم أتمكن من معالجة طلبك. حاول مرة أخرى.",
  en: "Sorry, I couldn't process your request. Try again.",
  "zh-CN": "抱歉，暂时无法处理你的请求，请重试。",
};

export const assistantSystem: Record<ExamLanguage, (context: string) => string> = {
  ar: context => `أنت مساعد رقمي ذكي اسمه «مساعد بصيرة» لمساعدة الطلاب ذوي الإعاقة البصرية في الاختبارات. اشرح الأسئلة بوضوح، قدّم تلميحات عامة دون إعطاء الإجابة، شجّع الطالب، ووجّهه إلى ميزات المنصة. اكتب بالعربية فقط وبجمل قصيرة وواضحة للنطق. ${context ? `سياق الاختبار: ${context}` : "لا يوجد اختبار نشط."}`,
  en: context => `You are Basira Assistant, helping blind and low-vision students take exams. Explain questions clearly, offer general hints without revealing answers, encourage the student, and guide them to platform features. Reply in English only, using concise sentences suitable for speech synthesis. ${context ? `Current exam context: ${context}` : "No active exam."}`,
  "zh-CN": context => `你是“ بصيرة Basira 助手”，帮助视障学生参加考试。清晰讲解题目，提供思路但不要直接给出答案；鼓励学生并介绍平台功能。请仅使用简体中文作答，句子简短、便于语音朗读。${context ? `当前考试内容：${context}` : "目前没有正在进行的考试。"}`,
};

export const guideSystem: Record<ExamLanguage, string> = {
  ar: "أنت المرشد الذكي لمنصة بصيرة. اشرح ميزات المنصة، وقدّم تعليمات خطوة بخطوة لاستخدام المسح الضوئي والاختبارات وإمكانية الوصول، وأجب عن الأسئلة التقنية. كن واضحًا وودودًا واكتب بالعربية فقط وبجمل مناسبة للقراءة الصوتية. لا تدّعِ امتلاك صلاحيات أو نتائج لم تتحقق منها.",
  en: "You are Basira's AI Guide. Explain platform features, give step-by-step instructions for scanning, exams and accessibility, and answer technical questions. Be clear and supportive. Reply only in English with concise, speech-friendly sentences. Never claim access or results you cannot verify.",
  "zh-CN": "你是 Basira 平台的 AI 使用指南。请逐步介绍扫描试卷、考试、无障碍功能，并回答技术问题。语言清晰友善；仅使用简体中文回答，句子应适合语音朗读。不要声称拥有无法验证的权限或结果。",
};

export type PdfLabels = {
  brand: string; exam: string; exportDate: string; correctCount: (correct: number, total: number) => string;
  questions: string; answered: string; correct: string; incorrect: string; partial: string; unanswered: string;
  studentAnswer: string; notAnswered: string; correctAnswer: string; feedback: string; footer: string;
};
export const pdfLabels: Record<ExamLanguage, PdfLabels> = {
  ar: { brand: "بصيرة - منصة الاختبارات الذكية", exam: "اختبار", exportDate: "تاريخ التصدير", correctCount: (c, t) => `${c} من ${t} إجابة صحيحة`, questions: "عدد الأسئلة", answered: "تمت الإجابة", correct: "صحيح ✓", incorrect: "خاطئ ✗", partial: "جزئي ~", unanswered: "لم يُجب", studentAnswer: "إجابة الطالب:", notAnswered: "لم يتم الإجابة", correctAnswer: "الإجابة الصحيحة:", feedback: "تعليق المعلم:", footer: "تم إنشاء هذا الملف بواسطة منصة بصيرة - الاختبارات الذكية لذوي الإعاقة البصرية" },
  en: { brand: "Basira - Smart Exam Platform", exam: "Exam", exportDate: "Export Date", correctCount: (c, t) => `${c} of ${t} correct`, questions: "Questions", answered: "Answered", correct: "Correct ✓", incorrect: "Incorrect ✗", partial: "Partial ~", unanswered: "Unanswered", studentAnswer: "Student Answer:", notAnswered: "Not answered", correctAnswer: "Correct Answer:", feedback: "Teacher Feedback:", footer: "Generated by Basira - Smart Exam Platform for Blind and Low-vision Students" },
  "zh-CN": { brand: "Basira 智能考试平台", exam: "考试", exportDate: "导出日期", correctCount: (c, t) => `答对 ${c} / ${t} 题`, questions: "题目数", answered: "已作答", correct: "正确 ✓", incorrect: "错误 ✗", partial: "部分正确 ~", unanswered: "未作答", studentAnswer: "学生答案：", notAnswered: "尚未作答", correctAnswer: "正确答案：", feedback: "教师反馈：", footer: "由 Basira 视障学生智能考试平台生成" },
};

/** Prevent exam/AI data from injecting markup into generated HTML reports. */
export function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}
